import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useDemo } from '../app/DemoContext'
import { ArticleTeaser } from '../components/Editorial'
import { PageIntro, Seo } from '../components/Primitives'
import { articles, projects } from '../data/seed'

export function PresentationPage() {
  return <><Seo title="Prezentare" description="Misiunea și principiile editoriale Bimael." /><PageIntro eyebrow="Despre platformă" title="Un salon pentru idei care cer timp"><p>Bimael leagă revista academică, arhiva culturală, programul de întâlniri și librăria într-o singură identitate editorială.</p></PageIntro><section className="shell manifesto-page"><div className="manifesto-number">I</div><article><span className="kicker">Misiune</span><h2>Rigoare fără rigiditate</h2><p>O cercetare poate fi precisă și ospitalieră în același timp. Publicul larg nu este tratat ca un cititor diminuat, iar autoritatea nu este confundată cu opacitatea.</p></article><div className="manifesto-number">II</div><article><span className="kicker">Metodă</span><h2>Etichete oneste</h2><p>Eseul, opinia, preprintul și studiul sunt prezentate distinct. Platforma nu revendică validare academică acolo unde nu există un proces real.</p></article><div className="manifesto-number">III</div><article><span className="kicker">Comunitate</span><h2>Întâlnirea continuă textul</h2><p>Webinariile, dezbaterile și evenimentele oferă context, nu doar conversie comercială.</p></article><aside><blockquote>„Fiecare pagină trebuie să pară parte din aceeași operă.”</blockquote><Link to="/autori">Cunoaște autorii</Link></aside></section></>
}

export function DebatesPage() {
  return <><Seo title="Dezbateri" description="Teze, antiteze și dialoguri moderate în Bimael." /><PageIntro eyebrow="Argument public" title="Dezbateri"><p>Poziții prezentate echitabil, surse comune și replici care clarifică în loc să amplifice zgomotul.</p></PageIntro><section className="shell debate-page"><header><span className="kicker">În desfășurare · moderată</span><h2>Poate o mașină să aibă o perspectivă?</h2><p>Moderator: Sofia Editor · 4 contribuții · bibliografie comună</p></header><div className="positions"><article><small>Teză</small><h3>Perspectiva cere un corp situat</h3><p>Experiența depinde de o istorie a vulnerabilității, a mișcării și a relației cu ceilalți.</p><strong>Ana-Maria Ilinca</strong></article><article><small>Antiteză</small><h3>Funcția poate preceda experiența</h3><p>Nu știm dacă o arhitectură funcțională suficient de bogată exclude din principiu perspectiva.</p><strong>Tudor Vlas</strong></article></div><ol className="debate-thread"><li><span>01</span><div><small>Argument central</small><h3>Ce numim „perspectivă”?</h3><p>Disputa începe prin separarea accesului informațional de caracterul trăit al experienței.</p></div></li><li><span>02</span><div><small>Replică</small><h3>Simularea nu rezolvă criteriul</h3><p>Comportamentul rămâne o dovadă, dar nu o traducere completă a persoanei întâi.</p></div></li></ol></section></>
}

export function StoriesPage() {
  return <><Seo title="Povești" description="Eseuri narative și istorii ale ideilor." /><PageIntro eyebrow="Narațiuni de cercetare" title="Povești"><p>Istorii în care arhiva, biografia și ideea se citesc împreună.</p></PageIntro><section className="shell story-grid"><article className="story-feature"><span className="kicker">Din arhivă</span><h2>Camera în care temperatura a devenit număr</h2><p>O poveste despre etaloane, dispute și liniștea aparentă a instrumentelor.</p><Link to="/articole/masura-si-metafizica">Citește povestea</Link></article><blockquote>„Marginalia spun uneori mai mult despre o epocă decât tratatul pe care îl înconjoară.”</blockquote><article><span className="kicker">Portret</span><h2>Un caiet de laborator și trei definiții ale atenției</h2><p>În pregătire · dosar editorial demo</p></article></section></>
}

export function ProjectsPage() {
  return <><Seo title="Proiecte" description="Proiecte de cercetare și arhive demonstrative Bimael." /><PageIntro eyebrow="Cercetare deschisă" title="Proiecte"><p>Inițiative în lucru, cu status și autor asumat.</p></PageIntro><section className="shell project-ledger large">{projects.map((project, index) => <article key={project.id}><span>{String(index + 1).padStart(2, '0')}</span><div><small>{project.status}</small><h2>{project.title}</h2><p>{project.description}</p><Link to={`/autori/${project.authorId === 'a-marian' ? 'marian-bituics' : project.authorId === 'a-ana' ? 'ana-maria-ilinca' : 'tudor-vlas'}/proiecte`}>Vezi autorul →</Link></div></article>)}</section></>
}

export function ArchivePage() {
  return <><Seo title="Arhivă" description="Arhiva cronologică Bimael." /><PageIntro eyebrow="Fond editorial" title="Arhivă"><p>Materiale ordonate după an, tip și domeniu. Pentru filtrare fină, folosește indexul de căutare.</p></PageIntro><section className="shell archive-page"><aside><span className="kicker">Ani</span><a href="#year-2026">2026</a><a href="#year-2025">2025</a></aside><div><section id="year-2026"><div className="section-rule"><h2>2026</h2><Link to="/cautare">Filtrează</Link></div>{articles.map((article) => <ArticleTeaser key={article.id} article={article} />)}</section><section id="year-2025"><div className="section-rule"><h2>2025</h2></div><p className="muted">Fondul 2025 este în curs de digitizare în setul demo.</p></section></div></section></>
}

export function InstitutionsPage() {
  const { sponsors } = useDemo()
  return <><Seo title="Instituții și parteneri" description="Partenerii demonstrativi ai platformei Bimael." /><PageIntro eyebrow="Rețea" title="Instituții & parteneri"><p>Colaborările de aici sunt fictive și nu reprezintă afilieri reale.</p></PageIntro><section className="shell institution-grid">{sponsors.map((sponsor, index) => <article key={sponsor.id}><span>{String(index + 1).padStart(2, '0')}</span><div className="institution-mark">{sponsor.name.split(' ').map((word) => word[0]).join('').slice(0, 3)}</div><h2>{sponsor.name}</h2><p>{sponsor.tier}</p></article>)}</section></>
}

export function ContactPage() {
  const [sent, setSent] = useState(false)
  return <><Seo title="Contact" description="Contactează echipa demonstrativă Bimael." /><PageIntro eyebrow="Corespondență" title="Contact"><p>Întrebări editoriale, propuneri de colaborare sau accesibilitate.</p></PageIntro><section className="shell contact-grid"><div><span className="kicker">Redacție demo</span><h2>Scrie-ne cu context</h2><p>În producție, mesajele vor fi preluate de un adapter de email și o politică de retenție. Aici nu părăsesc sesiunea.</p><dl><div><dt>Program</dt><dd>Luni–Joi · 10:00–16:00</dd></div><div><dt>Fus orar</dt><dd>Europe/Bucharest</dd></div><div><dt>Accesibilitate</dt><dd>Menționează formatul de răspuns preferat.</dd></div></dl></div>{sent ? <div className="success-panel" role="status"><h2>Mesaj înregistrat local</h2><p>Nu a fost trimis niciun email extern.</p><button type="button" onClick={() => setSent(false)}>Scrie alt mesaj</button></div> : <form className="editorial-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label htmlFor="general-name">Nume<input id="general-name" required /></label><label htmlFor="general-email">Email<input id="general-email" type="email" autoComplete="email" required /></label><label htmlFor="general-topic">Subiect<select id="general-topic"><option>Propunere editorială</option><option>Evenimente</option><option>Accesibilitate</option><option>Parteneriate</option></select></label><label htmlFor="general-message">Mesaj<textarea id="general-message" minLength={20} rows={6} required /></label><button className="primary-action" type="submit">Înregistrează mesajul demo</button></form>}</section></>
}

export function PolicyPage() {
  const { slug } = useParams()
  const privacy = slug === 'confidentialitate'
  return <><Seo title={privacy ? 'Confidențialitate' : 'Termeni demo'} description="Politicile mediului demonstrativ Bimael." /><PageIntro eyebrow="Politici" title={privacy ? 'Confidențialitate' : 'Termenii mediului demo'}><p>Document demonstrativ, nu consultanță juridică și nu politica finală a unui serviciu în producție.</p></PageIntro><article className="shell policy-copy"><h2>{privacy ? 'Ce date folosește demonstrația' : 'Ce înseamnă mediul demo'}</h2><p>{privacy ? 'Coșul, materialele salvate și istoricul vizibil sunt stocate în localStorage. Sesiunea de rol este semnată pe server și transmisă prin cookie HttpOnly. Serverul păstrează volatil newsletterul și acțiunile până la restart.' : 'Produsele, autorii, instituțiile, biletele și plățile sunt fictive. Nicio acțiune nu produce livrare, debitare, certificat sau afiliere academică reală.'}</p><h2>Controlul utilizatorului</h2><p>Butonul „Resetează datele locale” șterge starea persistentă a browserului. Într-un produs real, exportul și ștergerea contului vor necesita verificare suplimentară.</p><h2>Integrări externe</h2><p>Plățile, emailul și video folosesc adaptoare demo. Variabilele și limitele sunt documentate în repository.</p></article></>
}

export function ForbiddenPage() { return <><Seo title="Acces interzis" description="Rolul curent nu are acces la această zonă." /><section className="shell error-page"><span>403</span><h1>Accesul aparține altui rol</h1><p>Operația a fost oprită înainte de a ajunge la conținutul protejat. Intră cu rolul potrivit din pagina demo.</p><Link className="primary-action" to="/autentificare">Schimbă rolul</Link><Link to="/">Înapoi acasă</Link></section></> }
export function NotFoundPage() { return <><Seo title="Pagina nu există" description="Ruta cerută nu a fost găsită." /><section className="shell error-page"><span>404</span><h1>Fila lipsește din arhivă</h1><p>Adresa poate fi veche sau scrisă greșit.</p><Link className="primary-action" to="/cautare">Caută în Bimael</Link><Link to="/">Înapoi la copertă</Link></section></> }
